import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from './config.js';

const configured = SUPABASE_URL.startsWith('https://') && !SUPABASE_ANON_KEY.includes('COLE_AQUI');
const supabase = configured ? createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
const $ = (id) => document.getElementById(id);
const brl = (v) => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
const localDate = () => new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date());
const timeFmt = (iso) => new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',timeZone:'America/Sao_Paulo'}).format(new Date(iso));
const dateFmt = (date) => new Intl.DateTimeFormat('pt-BR',{dateStyle:'full',timeZone:'America/Sao_Paulo'}).format(date);
const state = { user:null, cash:null, sales:[], movements:[] };

function toast(msg,error=false){const el=$('toast');el.textContent=msg;el.className='toast show'+(error?' error':'');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.className='toast',2800)}
function showApp(on){$('loginView').classList.toggle('hidden',on);$('appView').classList.toggle('hidden',!on)}
function nav(section){document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.section===section));$('section-'+section).classList.add('active');const titles={dashboard:'Visão geral',sale:'Nova venda',cash:'Movimentações',history:'Histórico',close:'Fechamento'};$('pageTitle').textContent=titles[section];if(section==='history') loadHistory();if(section==='close') renderClose()}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>nav(b.dataset.section));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));

$('todayLabel').textContent=dateFmt(new Date()).toUpperCase();$('historyDate').value=localDate();
if(!configured){$('configWarning').classList.remove('hidden')}

$('loginForm').addEventListener('submit', async(e)=>{e.preventDefault();if(!supabase)return toast('Configure o Supabase no arquivo config.js.',true);const {data,error}=await supabase.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)return toast('E-mail ou senha inválidos.',true);state.user=data.user;showApp(true);await refreshAll()});
$('logoutBtn').onclick=async()=>{if(supabase)await supabase.auth.signOut();state.user=null;showApp(false)};

async function restore(){if(!supabase)return;const {data}=await supabase.auth.getSession();if(data.session){state.user=data.session.user;showApp(true);await refreshAll()}}

async function refreshAll(){await Promise.all([loadCash(),loadTodaySales(),loadMovements()]);renderDashboard();renderMovements();renderClose()}
async function loadCash(){const {data,error}=await supabase.from('cash_sessions').select('*').eq('user_id',state.user.id).eq('status','open').order('opened_at',{ascending:false}).limit(1);if(error){toast('Erro ao carregar o caixa.',true);return}state.cash=data?.[0]||null;renderCashStatus()}
function renderCashStatus(){const open=!!state.cash;$('cashStatus').textContent=open?'Caixa aberto':'Caixa fechado';$('cashStatus').classList.toggle('open',open);$('openCashBtn').classList.toggle('hidden',open)}

$('openCashBtn').onclick=()=>$('openCashDialog').showModal();$('confirmOpenCash').onclick=async(e)=>{e.preventDefault();const amount=Number($('openingAmount').value||0);const {error}=await supabase.from('cash_sessions').insert({user_id:state.user.id,opening_amount:amount,status:'open'});if(error)return toast('Não foi possível abrir o caixa.',true);$('openCashDialog').close();toast('Caixa aberto.');await refreshAll()};

async function loadTodaySales(){const start=localDate()+'T00:00:00-03:00',end=localDate()+'T23:59:59-03:00';const {data,error}=await supabase.from('sales').select('*,sale_items(*)').eq('user_id',state.user.id).gte('created_at',start).lte('created_at',end).order('created_at',{ascending:false});if(error)return toast('Erro ao carregar vendas.',true);state.sales=data||[]}
async function loadMovements(){if(!state.cash){state.movements=[];return}const {data,error}=await supabase.from('cash_movements').select('*').eq('cash_session_id',state.cash.id).order('created_at',{ascending:false});if(error)return toast('Erro ao carregar movimentações.',true);state.movements=data||[]}

function totals(){const salesTotal=state.sales.reduce((s,x)=>s+Number(x.total),0);const income=state.movements.filter(x=>x.type==='entrada').reduce((s,x)=>s+Number(x.amount),0);const expense=state.movements.filter(x=>x.type==='saida').reduce((s,x)=>s+Number(x.amount),0);const opening=Number(state.cash?.opening_amount||0);const cashSales=state.sales.filter(x=>x.payment_method==='dinheiro').reduce((s,x)=>s+Number(x.total),0);return{salesTotal,income,expense,opening,balance:opening+salesTotal+income-expense,expectedCash:opening+cashSales+income-expense}}
function renderDashboard(){const t=totals();$('metricSales').textContent=brl(t.salesTotal);$('metricSalesCount').textContent=`${state.sales.length} ${state.sales.length===1?'venda':'vendas'}`;$('metricIncome').textContent=brl(t.income);$('metricExpense').textContent=brl(t.expense);$('metricBalance').textContent=brl(t.balance);const methods={pix:'Pix',dinheiro:'Dinheiro',debito:'Débito',credito:'Crédito',outro:'Outro'};const sums={};state.sales.forEach(s=>sums[s.payment_method]=(sums[s.payment_method]||0)+Number(s.total));const max=Math.max(1,...Object.values(sums));$('paymentSummary').innerHTML=Object.keys(methods).map(k=>`<div class="payment-row"><span>${methods[k]}</span><div class="payment-bar"><div class="payment-fill" style="width:${((sums[k]||0)/max)*100}%"></div></div><strong>${brl(sums[k]||0)}</strong></div>`).join('');$('recentSales').className=state.sales.length?'':'list-empty';$('recentSales').innerHTML=state.sales.length?state.sales.slice(0,5).map(s=>`<div class="recent-row"><div><strong>${escapeHtml(s.customer_name||'Venda balcão')}</strong><small>${timeFmt(s.created_at)} • ${methods[s.payment_method]||s.payment_method}</small></div><strong>${brl(s.total)}</strong></div>`).join(''):'Nenhuma venda registrada hoje.'}

let itemId=0;function addItem(){itemId++;const row=document.createElement('div');row.className='sale-item';row.dataset.id=itemId;row.innerHTML=`<label>Descrição<input class="item-desc" placeholder="Ex.: Cartão de visita" required></label><label>Qtd.<input class="item-qty" type="number" min="1" step="1" value="1"></label><label>Valor un.<input class="item-price" type="number" min="0" step="0.01" value="0"></label><button class="icon-btn" title="Remover">×</button>`;row.querySelectorAll('input').forEach(i=>i.addEventListener('input',calcSale));row.querySelector('.icon-btn').onclick=()=>{row.remove();calcSale()};$('saleItems').appendChild(row);calcSale()}
$('addItemBtn').onclick=addItem;$('saleDiscount').addEventListener('input',calcSale);function calcSale(){let sub=0;document.querySelectorAll('.sale-item').forEach(r=>sub+=Number(r.querySelector('.item-qty').value||0)*Number(r.querySelector('.item-price').value||0));const discount=Math.min(Number($('saleDiscount').value||0),sub);$('saleSubtotal').textContent=brl(sub);$('saleTotal').textContent=brl(Math.max(0,sub-discount));return{sub,discount,total:Math.max(0,sub-discount)}}addItem();

$('finishSaleBtn').onclick=async()=>{if(!state.cash)return toast('Abra o caixa antes de registrar uma venda.',true);const items=[...document.querySelectorAll('.sale-item')].map(r=>({description:r.querySelector('.item-desc').value.trim(),quantity:Number(r.querySelector('.item-qty').value||0),unit_price:Number(r.querySelector('.item-price').value||0)})).filter(x=>x.description&&x.quantity>0);if(!items.length)return toast('Adicione pelo menos um item.',true);const c=calcSale();if(c.total<=0)return toast('O total da venda deve ser maior que zero.',true);const payload={user_id:state.user.id,cash_session_id:state.cash.id,customer_name:$('saleCustomer').value.trim()||null,note:$('saleNote').value.trim()||null,subtotal:c.sub,discount:c.discount,total:c.total,payment_method:$('salePayment').value};const {data:sale,error}=await supabase.from('sales').insert(payload).select().single();if(error)return toast('Erro ao registrar a venda.',true);const rows=items.map(i=>({...i,sale_id:sale.id,total:i.quantity*i.unit_price}));const {error:itemErr}=await supabase.from('sale_items').insert(rows);if(itemErr)return toast('Venda criada, mas houve erro nos itens.',true);$('saleCustomer').value='';$('saleNote').value='';$('saleDiscount').value='0';$('saleItems').innerHTML='';addItem();toast('Venda finalizada.');await refreshAll();nav('dashboard')};

$('movementForm').addEventListener('submit',async e=>{e.preventDefault();if(!state.cash)return toast('Abra o caixa primeiro.',true);const amount=Number($('movementAmount').value);if(!(amount>0))return toast('Informe um valor válido.',true);const {error}=await supabase.from('cash_movements').insert({cash_session_id:state.cash.id,user_id:state.user.id,type:$('movementType').value,description:$('movementDescription').value.trim(),amount});if(error)return toast('Erro ao registrar movimentação.',true);e.target.reset();toast('Movimentação registrada.');await refreshAll()});
function renderMovements(){$('movementList').className=state.movements.length?'':'list-empty';$('movementList').innerHTML=state.movements.length?state.movements.map(m=>`<div class="movement-row"><div><strong>${escapeHtml(m.description)}</strong><small>${timeFmt(m.created_at)} • ${m.type}</small></div><strong class="${m.type==='entrada'?'money-in':'money-out'}">${m.type==='entrada'?'+':'−'} ${brl(m.amount)}</strong></div>`).join(''):'Nenhuma movimentação registrada.'}

$('historyDate').addEventListener('change',loadHistory);async function loadHistory(){if(!supabase||!state.user)return;const d=$('historyDate').value||localDate();const {data,error}=await supabase.from('sales').select('*,sale_items(*)').eq('user_id',state.user.id).gte('created_at',d+'T00:00:00-03:00').lte('created_at',d+'T23:59:59-03:00').order('created_at',{ascending:false});if(error)return toast('Erro ao carregar histórico.',true);const methods={pix:'Pix',dinheiro:'Dinheiro',debito:'Débito',credito:'Crédito',outro:'Outro'};$('historyBody').innerHTML=(data||[]).map(s=>`<tr><td>${timeFmt(s.created_at)}</td><td>${escapeHtml(s.customer_name||'Venda balcão')}</td><td>${methods[s.payment_method]||s.payment_method}</td><td>${s.sale_items?.length||0}</td><td><strong>${brl(s.total)}</strong></td></tr>`).join('')||'<tr><td colspan="5" class="list-empty">Nenhuma venda nesta data.</td></tr>'}

function renderClose(){const t=totals();$('closeSummary').innerHTML=`<div class="close-line"><span>Fundo inicial</span><strong>${brl(t.opening)}</strong></div><div class="close-line"><span>Vendas</span><strong>${brl(t.salesTotal)}</strong></div><div class="close-line"><span>Entradas</span><strong>${brl(t.income)}</strong></div><div class="close-line"><span>Saídas</span><strong>− ${brl(t.expense)}</strong></div><div class="close-line total"><span>Saldo esperado geral</span><strong>${brl(t.balance)}</strong></div><div class="close-line"><span>Dinheiro esperado em espécie</span><strong>${brl(t.expectedCash)}</strong></div>`;$('closeCashBtn').disabled=!state.cash}
$('closeCashBtn').onclick=async()=>{if(!state.cash)return toast('Não há caixa aberto.',true);const counted=Number($('countedCash').value||0),t=totals(),difference=counted-t.expectedCash;const {error}=await supabase.from('cash_sessions').update({status:'closed',closed_at:new Date().toISOString(),counted_cash:counted,expected_cash:t.expectedCash,difference,closing_note:$('closeNote').value.trim()||null}).eq('id',state.cash.id);if(error)return toast('Erro ao fechar o caixa.',true);toast(`Caixa fechado. Diferença: ${brl(difference)}`);$('countedCash').value='0';$('closeNote').value='';await refreshAll();nav('dashboard')};

function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
restore();
