import {supabase,db} from './erp-db.js';

const $=id=>document.getElementById(id);
const $$=sel=>[...document.querySelectorAll(sel)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const brl=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date());
const dateBR=v=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(v.length===10?`${v}T12:00:00-03:00`:v)):'—';
const dateTimeBR=v=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(v)):'—';
const SELLERS=['IGOR','JHONATAN','BEATRIZ'];
const ORDER_STATUS={approved:'Aprovado',art:'Arte',waiting_approval:'Aguardando aprovação',print_queue:'Fila de impressão',printing:'Imprimindo',finishing:'Acabamento',cutting:'Corte',assembly:'Montagem',quality:'Conferência',ready:'Pronto',delivered:'Entregue',cancelled:'Cancelado'};
let snapshot={customers:[],orders:[],quotes:[],tasks:[],products:[],receivables:[]};
let commandRows=[];
let commandIndex=0;
let quickParseTimer=null;

function notice(msg,error=false){const el=$('toast');if(!el)return;el.textContent=msg;el.className=`toast show${error?' error':''}`;clearTimeout(window.__quickToast);window.__quickToast=setTimeout(()=>el.className='toast',3000)}
function isTypingTarget(el){return !!el&&(el.matches?.('input,textarea,select')||el.isContentEditable)}
function dialogOpen(){return !!document.querySelector('dialog[open]')}
function plusDays(days){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+days);return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(d)}
function ageDays(v){if(!v)return 0;return Math.floor((Date.now()-new Date(v).getTime())/86400000)}
function openTask(t){return !['done','cancelled'].includes(t.status)}
function openOrder(o){return !['ready','delivered','cancelled'].includes(o.status)}

async function ensureDb(){const {data}=await supabase.auth.getSession();const user=data.session?.user;if(!user)return null;db.setUser(user);await db.detectERP();return user}
async function loadSnapshot(){if(!await ensureDb())return snapshot;const [customers,orders,quotes,tasks,products,receivables]=await Promise.all(['customers','orders','quotes','tasks','products','receivables'].map(x=>db.list(x)));snapshot={customers,orders,quotes,tasks,products,receivables};return snapshot}

function injectStyle(){if(document.querySelector('link[data-quick-ops]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./quick-ops.css?build=20260831-1455';l.dataset.quickOps='1';document.head.appendChild(l)}

function injectCreateMenu(){if($('quickCreateMenu'))return;document.body.insertAdjacentHTML('beforeend',`
  <div id="quickCreateMenu" class="quick-menu" aria-hidden="true">
    <div class="quick-menu-head"><div><strong>Criar rapidamente</strong><span>Sem procurar módulo no menu</span></div><span>ESC fecha</span></div>
    <div class="quick-menu-grid">
      <button class="quick-action task" data-quick-action="task"><i>✓</i><span><b>Nova tarefa</b><small>Registre em poucos segundos</small></span></button>
      <button class="quick-action" data-quick-action="sale"><i>＋</i><span><b>Nova venda</b><small>Venda rápida de balcão</small></span></button>
      <button class="quick-action" data-quick-action="quote"><i>▤</i><span><b>Novo orçamento</b><small>Cliente, itens e margem</small></span></button>
      <button class="quick-action" data-quick-action="customer"><i>◎</i><span><b>Novo cliente</b><small>Cadastro comercial</small></span></button>
      <button class="quick-action" data-quick-action="order"><i>▣</i><span><b>Novo pedido</b><small>Pedido manual</small></span></button>
      <button class="quick-action" data-quick-action="lead"><i>◇</i><span><b>Novo atendimento</b><small>Entrada no CRM</small></span></button>
      <button class="quick-action finance" data-quick-action="movement"><i>R$</i><span><b>Novo lançamento</b><small>Entrada ou saída do caixa</small></span></button>
      <button class="quick-action finance" data-quick-action="receivable"><i>↙</i><span><b>Conta a receber</b><small>Valor e vencimento</small></span></button>
      <button class="quick-action finance" data-quick-action="payable"><i>↗</i><span><b>Conta a pagar</b><small>Fornecedor e centro de custo</small></span></button>
      <button class="quick-action stock" data-quick-action="stock"><i>▥</i><span><b>Novo insumo</b><small>Adicionar ao estoque</small></span></button>
    </div>
  </div>`);
  $('quickCreateMenu').addEventListener('click',e=>{const b=e.target.closest('[data-quick-action]');if(!b)return;closeCreateMenu();runQuickAction(b.dataset.quickAction)});
}
function toggleCreateMenu(){const m=$('quickCreateMenu');if(!m)return;m.classList.toggle('open');m.setAttribute('aria-hidden',m.classList.contains('open')?'false':'true')}
function closeCreateMenu(){const m=$('quickCreateMenu');m?.classList.remove('open');m?.setAttribute('aria-hidden','true')}

function clickNav(section){const b=document.querySelector(`.nav-item[data-section="${section}"]`);b?.click()}
function openExisting(section,buttonId,after=null){closeCreateMenu();clickNav(section);setTimeout(()=>{$(buttonId)?.click();if(after)setTimeout(after,30)},30)}
function runQuickAction(action){const map={sale:()=>clickNav('sale'),quote:()=>openExisting('quotes','newQuoteBtn'),customer:()=>openExisting('customers','newCustomerBtn'),order:()=>openExisting('orders','newOrderBtn'),lead:()=>openExisting('funnel','newLeadBtn'),movement:()=>openExisting('ledger','newMovementBtn'),receivable:()=>openExisting('finance','newReceivableBtn'),payable:()=>openExisting('finance','newPayableBtn'),stock:()=>openExisting('stock','newStockBtn'),task:()=>openQuickTask()};map[action]?.()}

function injectToday(){if($('section-today'))return;const nav=document.querySelector('.nav-item[data-section="dashboard"]');if(nav){const b=document.createElement('button');b.className='nav-item';b.dataset.section='today';b.innerHTML='<span>◷</span>Hoje';nav.insertAdjacentElement('afterend',b);b.onclick=showToday}
  const dashboard=$('section-dashboard');if(dashboard){const s=document.createElement('section');s.id='section-today';s.className='section';s.innerHTML=`
    <div class="today-shell">
      <article class="today-focus">
        <p class="eyebrow light">CENTRO OPERACIONAL</p><h3>O que precisa acontecer hoje?</h3><p>Registre uma tarefa sem abrir formulário. Escreva como você fala.</p>
        <div class="today-capture"><input id="todayQuickCapture" placeholder="Ex.: revisar arte da caixa amanhã 14h para Beatriz"><button id="todayCaptureBtn">Criar tarefa</button></div>
        <div class="today-shortcuts"><button data-today-action="task">T · Nova tarefa</button><button data-today-action="sale">N · Venda</button><button data-today-action="quote">O · Orçamento</button><button data-today-action="customer">C · Cliente</button></div>
      </article>
      <div class="today-summary">
        <article class="today-number"><span>Tarefas para agir</span><strong id="todayTaskCount">0</strong><small id="todayTaskSub">0 atrasadas</small></article>
        <article class="today-number"><span>Pedidos no prazo</span><strong id="todayOrderCount">0</strong><small id="todayOrderSub">0 em risco</small></article>
        <article class="today-number"><span>Follow-ups</span><strong id="todayFollowCount">0</strong><small>orçamentos para retomar</small></article>
        <article class="today-number"><span>Financeiro</span><strong id="todayFinanceCount">0</strong><small id="todayFinanceSub">vencimentos e atrasos</small></article>
      </div>
    </div>
    <div class="today-grid">
      <article class="today-panel"><div class="today-panel-head"><div><h3>Tarefas</h3><small>Hoje + atrasadas</small></div><button class="today-link" data-open-section="tasks">Ver todas</button></div><div id="todayTasksList"></div></article>
      <article class="today-panel"><div class="today-panel-head"><div><h3>Pedidos</h3><small>Prazo hoje + atrasados</small></div><button class="today-link" data-open-section="production">Abrir produção</button></div><div id="todayOrdersList"></div></article>
      <article class="today-panel"><div class="today-panel-head"><div><h3>Comercial</h3><small>Orçamentos que pedem contato</small></div><button class="today-link" data-open-section="quotes">Abrir orçamentos</button></div><div id="todayFollowList"></div></article>
      <article class="today-panel"><div class="today-panel-head"><div><h3>Financeiro</h3><small>Contas vencendo ou vencidas</small></div><button class="today-link" data-open-section="finance">Abrir financeiro</button></div><div id="todayFinanceList"></div></article>
    </div>`;dashboard.insertAdjacentElement('beforebegin',s)}
  $('todayCaptureBtn')?.addEventListener('click',captureTodayTask);$('todayQuickCapture')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();captureTodayTask()}});
  $$('[data-today-action]').forEach(b=>b.onclick=()=>runQuickAction(b.dataset.todayAction));$$('[data-open-section]').forEach(b=>b.onclick=()=>clickNav(b.dataset.openSection));
}
function showToday(){closeCreateMenu();$$('.section').forEach(x=>x.classList.remove('active'));$('section-today')?.classList.add('active');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.section==='today'));if($('pageTitle'))$('pageTitle').textContent='Hoje';$('sidebar')?.classList.remove('open');renderToday()}

function injectDashboardDay(){if($('dashboardDay'))return;const hero=document.querySelector('#section-dashboard .hero-grid');if(!hero)return;hero.insertAdjacentHTML('afterend',`<article id="dashboardDay" class="dashboard-day"><div class="dashboard-day-head"><div><h3>Hoje na gráfica</h3><p>O que merece ação antes de você olhar relatórios.</p></div><div class="dashboard-day-actions"><button id="dashboardQuickTask" class="small-btn quick-context-btn">+ Tarefa</button><button id="dashboardOpenToday" class="small-btn primary">Abrir Hoje</button></div></div><div class="dashboard-day-grid"><div class="dashboard-day-col"><span>Tarefas</span><div id="dashboardDayTasks"></div></div><div class="dashboard-day-col"><span>Pedidos</span><div id="dashboardDayOrders"></div></div><div class="dashboard-day-col"><span>Atenção</span><div id="dashboardDayAttention"></div></div></div></article>`);$('dashboardQuickTask').onclick=()=>openQuickTask();$('dashboardOpenToday').onclick=showToday}

function rowHtml(main,sub,badge='',badgeClass=''){return`<div class="today-row"><div class="today-row-main"><b>${esc(main)}</b><small>${esc(sub)}</small></div>${badge?`<span class="today-badge ${badgeClass}">${esc(badge)}</span>`:''}</div>`}
function dashLine(main,side=''){return`<div class="dashboard-day-line"><b>${esc(main)}</b><small>${esc(side)}</small></div>`}

async function renderToday(){const s=await loadSnapshot(),today=localDate(),now=new Date();const tasks=s.tasks.filter(openTask),lateTasks=tasks.filter(t=>t.due_at&&new Date(t.due_at)<now),todayTasks=tasks.filter(t=>String(t.due_at||'').slice(0,10)===today),actionTasks=[...new Map([...lateTasks,...todayTasks].map(x=>[x.id,x])).values()].sort((a,b)=>(a.due_at||'9999').localeCompare(b.due_at||'9999'));const orders=s.orders.filter(openOrder),lateOrders=orders.filter(o=>o.promised_date&&o.promised_date<today),todayOrders=orders.filter(o=>o.promised_date===today),actionOrders=[...lateOrders,...todayOrders].sort((a,b)=>(a.promised_date||'9999').localeCompare(b.promised_date||'9999'));const follow=s.quotes.filter(q=>['sent','waiting'].includes(q.status)&&ageDays(q.updated_at||q.sent_at||q.created_at)>=2).sort((a,b)=>new Date(a.updated_at||a.created_at)-new Date(b.updated_at||b.created_at));const fin=s.receivables.filter(r=>r.status!=='paid'&&r.status!=='cancelled'&&r.due_date&&r.due_date<=today).sort((a,b)=>a.due_date.localeCompare(b.due_date));
  if($('todayTaskCount'))$('todayTaskCount').textContent=actionTasks.length;if($('todayTaskSub'))$('todayTaskSub').textContent=`${lateTasks.length} atrasada${lateTasks.length===1?'':'s'}`;if($('todayOrderCount'))$('todayOrderCount').textContent=actionOrders.length;if($('todayOrderSub'))$('todayOrderSub').textContent=`${lateOrders.length} em risco`;if($('todayFollowCount'))$('todayFollowCount').textContent=follow.length;if($('todayFinanceCount'))$('todayFinanceCount').textContent=fin.length;if($('todayFinanceSub'))$('todayFinanceSub').textContent=fin.length?brl(fin.reduce((a,r)=>a+Math.max(0,Number(r.amount)-Number(r.received_amount||0)),0)):'sem pendências';
  if($('todayTasksList'))$('todayTasksList').innerHTML=actionTasks.slice(0,7).map(t=>`<div class="today-row"><button class="today-check" data-complete-task="${t.id}" title="Concluir">✓</button><div class="today-row-main"><b>${esc(t.title)}</b><small>${esc(t.assignee||'sem responsável')} · ${t.due_at?dateTimeBR(t.due_at):'sem prazo'}</small></div><span class="today-badge ${lateTasks.some(x=>x.id===t.id)?'late':'today'}">${lateTasks.some(x=>x.id===t.id)?'atrasada':'hoje'}</span></div>`).join('')||'<div class="today-empty">Nenhuma tarefa urgente hoje.</div>';
  if($('todayOrdersList'))$('todayOrdersList').innerHTML=actionOrders.slice(0,7).map(o=>rowHtml(`${o.code||'Pedido'} · ${customerById(o.customer_id)}`,`${ORDER_STATUS[o.status]||o.status} · ${brl(o.total)}`,o.promised_date<today?'atrasado':'hoje',o.promised_date<today?'late':'today')).join('')||'<div class="today-empty">Nenhum pedido vencendo hoje.</div>';
  if($('todayFollowList'))$('todayFollowList').innerHTML=follow.slice(0,7).map(q=>rowHtml(`${q.code||'Orçamento'} · ${customerById(q.customer_id)}`,`${brl(q.total)} · ${ageDays(q.updated_at||q.created_at)} dias sem avanço`,'retomar','today')).join('')||'<div class="today-empty">Nenhum follow-up pendente.</div>';
  if($('todayFinanceList'))$('todayFinanceList').innerHTML=fin.slice(0,7).map(r=>rowHtml(r.description||'Conta a receber',`${customerById(r.customer_id)} · ${brl(Math.max(0,Number(r.amount)-Number(r.received_amount||0)))}`,r.due_date<today?'vencida':'hoje',r.due_date<today?'late':'today')).join('')||'<div class="today-empty">Nenhum recebimento vencendo hoje.</div>';
  $$('[data-complete-task]').forEach(b=>b.onclick=async()=>{await ensureDb();await db.update('tasks',b.dataset.completeTask,{status:'done',completed_at:new Date().toISOString()});notice('Tarefa concluída.');await renderQuickSurfaces();refreshMainSoon()});
  renderDashboardDayFrom(s,{actionTasks,actionOrders,follow,fin,lateTasks,lateOrders})
}
function customerById(id){return snapshot.customers.find(c=>c.id===id)?.name||'Cliente não informado'}
function renderDashboardDayFrom(s,d=null){if(!$('dashboardDay'))return;if(!d){const today=localDate(),now=new Date(),tasks=s.tasks.filter(openTask),lateTasks=tasks.filter(t=>t.due_at&&new Date(t.due_at)<now),todayTasks=tasks.filter(t=>String(t.due_at||'').slice(0,10)===today),actionTasks=[...new Map([...lateTasks,...todayTasks].map(x=>[x.id,x])).values()],orders=s.orders.filter(openOrder),lateOrders=orders.filter(o=>o.promised_date&&o.promised_date<today),todayOrders=orders.filter(o=>o.promised_date===today),actionOrders=[...lateOrders,...todayOrders],follow=s.quotes.filter(q=>['sent','waiting'].includes(q.status)&&ageDays(q.updated_at||q.created_at)>=2),fin=s.receivables.filter(r=>r.status!=='paid'&&r.due_date&&r.due_date<=today);d={actionTasks,actionOrders,follow,fin,lateTasks,lateOrders}}
  $('dashboardDayTasks').innerHTML=d.actionTasks.slice(0,3).map(t=>dashLine(t.title,t.due_at?dateTimeBR(t.due_at):'sem prazo')).join('')||dashLine('Sem tarefas críticas','');$('dashboardDayOrders').innerHTML=d.actionOrders.slice(0,3).map(o=>dashLine(`${o.code||'Pedido'} · ${customerById(o.customer_id)}`,o.promised_date?dateBR(o.promised_date):'sem prazo')).join('')||dashLine('Nenhum prazo crítico','');const attention=[d.follow.length&&`${d.follow.length} follow-up(s)`,d.fin.length&&`${d.fin.length} recebimento(s)`,d.lateTasks.length&&`${d.lateTasks.length} tarefa(s) atrasada(s)`].filter(Boolean);$('dashboardDayAttention').innerHTML=attention.map(x=>dashLine(x,'')).join('')||dashLine('Operação sob controle','')
}
async function renderQuickSurfaces(){injectDashboardDay();const s=await loadSnapshot();renderDashboardDayFrom(s);if($('section-today')?.classList.contains('active'))await renderToday();decorateContexts()}

function parseNaturalTask(raw,defaultToday=false){const original=String(raw||'').trim();let lower=original.toLowerCase(),assignee=null,priority='normal',date='',time='';for(const s of SELLERS){if(lower.includes(s.toLowerCase())){assignee=s;break}}if(/\b(urgente|cr[ií]tic[ao]|prioridade m[aá]xima)\b/i.test(original))priority='critical';else if(/\b(alta|prioridade alta|importante)\b/i.test(original))priority='high';if(/amanh[ãa]/i.test(original))date=plusDays(1);else if(/\bhoje\b/i.test(original))date=localDate();else if(defaultToday)date=localDate();const tm=original.match(/(?:às?|as)?\s*(\d{1,2})(?::(\d{2}))?\s*h\b/i)||original.match(/(?:às?|as)\s*(\d{1,2})(?::(\d{2}))?/i);if(tm){time=`${String(Math.min(23,Number(tm[1]))).padStart(2,'0')}:${String(Math.min(59,Number(tm[2]||0))).padStart(2,'0')}`;if(!date)date=localDate()}if(date&&!time)time=defaultToday?'17:00':'09:00';let title=original.replace(/\b(hoje|amanh[ãa]|urgente|cr[ií]tic[ao]|prioridade alta|prioridade m[aá]xima|importante)\b/gi,' ').replace(/\bpara\s+(igor|jhonatan|beatriz)\b/gi,' ').replace(/(?:às?|as)?\s*\d{1,2}(?::\d{2})?\s*h\b/gi,' ').replace(/\s{2,}/g,' ').trim().replace(/^[,;:\-\s]+|[,;:\-\s]+$/g,'');if(title.length<3)title=original;return{title,assignee,priority,date,time}}
async function createTaskFromNatural(text,defaultToday=true){const p=parseNaturalTask(text,defaultToday);if(!p.title)return notice('Escreva a tarefa.',true);if(!await ensureDb())return notice('Faça login novamente.',true);let due_at=null;if(p.date)due_at=new Date(`${p.date}T${p.time||'09:00'}:00`).toISOString();await db.insert('tasks',{title:p.title,status:'todo',priority:p.priority,assignee:p.assignee,due_at,description:null,estimated_minutes:null});notice('Tarefa criada.');await renderQuickSurfaces();refreshMainSoon();return true}
async function captureTodayTask(){const input=$('todayQuickCapture'),text=input?.value.trim();if(!text)return notice('Digite o que precisa ser feito.',true);if(await createTaskFromNatural(text,true))input.value=''}

function injectQuickTaskDialog(){if($('quickTaskDialog'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="quickTaskDialog" class="quick-dialog"><form id="quickTaskForm"><div class="quick-dialog-head"><div><h3>Nova tarefa</h3><p>O básico fica na frente. O resto só aparece se você precisar.</p></div><button type="button" class="quick-close" id="quickTaskClose">×</button></div><div class="quick-dialog-body quick-form"><div class="quick-natural"><label>Escreva como você fala</label><input id="quickNaturalTask" placeholder="Ex.: conferir corte do pedido amanhã 14h para Jhonatan"><small>Reconhece hoje, amanhã, horário, responsável e urgência.</small></div><label>O que precisa ser feito?<input id="quickTaskTitle" required></label><div class="quick-date-chips"><button type="button" class="quick-chip" data-date-chip="today">Hoje</button><button type="button" class="quick-chip" data-date-chip="tomorrow">Amanhã</button><button type="button" class="quick-chip" data-date-chip="week">+ 7 dias</button><button type="button" class="quick-chip" data-date-chip="none">Sem prazo</button></div><div class="quick-form-grid"><label>Data<input id="quickTaskDate" type="date"></label><label>Horário<input id="quickTaskTime" type="time" value="09:00"></label><label>Responsável<select id="quickTaskAssignee"><option value="">Sem responsável</option>${SELLERS.map(x=>`<option>${x}</option>`).join('')}</select></label></div><label>Prioridade<select id="quickTaskPriority"><option value="normal">Normal</option><option value="high">Alta</option><option value="critical">Urgente</option><option value="low">Baixa</option></select></label><details class="quick-details"><summary>Mais opções</summary><div class="quick-form-grid two"><label>Cliente<select id="quickTaskCustomer"><option value="">Nenhum</option></select></label><label>Pedido<select id="quickTaskOrder"><option value="">Nenhum</option></select></label></div><label>Descrição<textarea id="quickTaskDescription"></textarea></label></details></div><div class="quick-dialog-foot"><button type="button" class="quick-secondary" id="quickTaskCancel">Cancelar</button><button type="submit" class="quick-primary">Criar tarefa</button></div></form></dialog>`);
  $('quickTaskClose').onclick=()=>$('quickTaskDialog').close();$('quickTaskCancel').onclick=()=>$('quickTaskDialog').close();$$('[data-date-chip]').forEach(b=>b.onclick=()=>setTaskDateChip(b.dataset.dateChip));$('quickNaturalTask').addEventListener('input',()=>{clearTimeout(quickParseTimer);quickParseTimer=setTimeout(()=>applyNaturalToQuickForm($('quickNaturalTask').value),320)});$('quickNaturalTask').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();applyNaturalToQuickForm(e.target.value);$('quickTaskTitle').focus()}});$('quickTaskForm').onsubmit=saveQuickTask;
}
function setTaskDateChip(kind){const map={today:localDate(),tomorrow:plusDays(1),week:plusDays(7),none:''};$('quickTaskDate').value=map[kind]??'';$$('[data-date-chip]').forEach(b=>b.classList.toggle('active',b.dataset.dateChip===kind));if(kind!=='none'&&!$('quickTaskTime').value)$('quickTaskTime').value='09:00'}
function applyNaturalToQuickForm(text){if(!text.trim())return;const p=parseNaturalTask(text,false);$('quickTaskTitle').value=p.title||text;if(p.date)$('quickTaskDate').value=p.date;if(p.time)$('quickTaskTime').value=p.time;if(p.assignee)$('quickTaskAssignee').value=p.assignee;$('quickTaskPriority').value=p.priority;$$('[data-date-chip]').forEach(b=>b.classList.remove('active'))}
async function openQuickTask(pref={}){closeCreateMenu();injectQuickTaskDialog();const s=await loadSnapshot();$('quickTaskForm').reset();$('quickTaskTime').value='09:00';$('quickTaskPriority').value=pref.priority||'normal';$('quickTaskCustomer').innerHTML='<option value="">Nenhum</option>'+s.customers.sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('quickTaskOrder').innerHTML='<option value="">Nenhum</option>'+s.orders.filter(o=>!['delivered','cancelled'].includes(o.status)).map(o=>`<option value="${o.id}">${esc(o.code||'Pedido')} · ${esc(customerById(o.customer_id))}</option>`).join('');if(pref.customer_id)$('quickTaskCustomer').value=pref.customer_id;if(pref.order_id){$('quickTaskOrder').value=pref.order_id;const o=s.orders.find(x=>x.id===pref.order_id);if(o?.customer_id)$('quickTaskCustomer').value=o.customer_id}if(pref.title)$('quickTaskTitle').value=pref.title;if(pref.text){$('quickNaturalTask').value=pref.text;applyNaturalToQuickForm(pref.text)}if(pref.date)$('quickTaskDate').value=pref.date;$$('[data-date-chip]').forEach(b=>b.classList.remove('active'));$('quickTaskDialog').showModal();setTimeout(()=>$(pref.text?'quickTaskTitle':'quickNaturalTask').focus(),30)}
async function saveQuickTask(e){e.preventDefault();if(!await ensureDb())return notice('Faça login novamente.',true);const title=$('quickTaskTitle').value.trim();if(!title)return notice('Informe a tarefa.',true);const date=$('quickTaskDate').value,time=$('quickTaskTime').value||'09:00',order_id=$('quickTaskOrder').value||null;let customer_id=$('quickTaskCustomer').value||null;if(order_id&&!customer_id)customer_id=snapshot.orders.find(o=>o.id===order_id)?.customer_id||null;await db.insert('tasks',{title,status:'todo',priority:$('quickTaskPriority').value,assignee:$('quickTaskAssignee').value||null,due_at:date?new Date(`${date}T${time}:00`).toISOString():null,customer_id,order_id,description:$('quickTaskDescription').value.trim()||null,estimated_minutes:null});$('quickTaskDialog').close();notice('Tarefa criada.');await renderQuickSurfaces();refreshMainSoon()}

function injectCommandDialog(){if($('quickCommandDialog'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="quickCommandDialog" class="quick-dialog command"><div class="quick-command-input"><span>⌕</span><input id="quickCommandInput" autocomplete="off" placeholder="Buscar ou comandar... ex.: nova tarefa"><kbd>ESC</kbd></div><div id="quickCommandResults" class="quick-command-results"></div></dialog>`);$('quickCommandInput').oninput=e=>renderCommand(e.target.value);$('quickCommandInput').onkeydown=e=>{if(e.key==='ArrowDown'){e.preventDefault();moveCommand(1)}else if(e.key==='ArrowUp'){e.preventDefault();moveCommand(-1)}else if(e.key==='Enter'){e.preventDefault();commandRows[commandIndex]?.run?.()}else if(e.key==='Escape')$('quickCommandDialog').close()}}
async function openCommand(query=''){closeCreateMenu();injectCommandDialog();await loadSnapshot();const d=$('quickCommandDialog');if(!d.open)d.showModal();$('quickCommandInput').value=query;renderCommand(query);setTimeout(()=>$('quickCommandInput').focus(),25)}
function commandDefinitions(){return[
  {icon:'✓',label:'Nova tarefa',sub:'Criar em poucos segundos',keys:'t tarefa',run:()=>{$('quickCommandDialog').close();openQuickTask()}},
  {icon:'＋',label:'Nova venda',sub:'Abrir venda rápida',keys:'n venda',run:()=>{$('quickCommandDialog').close();clickNav('sale')}},
  {icon:'▤',label:'Novo orçamento',sub:'Criar proposta',keys:'o orçamento orcamento',run:()=>{$('quickCommandDialog').close();openExisting('quotes','newQuoteBtn')}},
  {icon:'◎',label:'Novo cliente',sub:'Cadastrar cliente',keys:'c cliente',run:()=>{$('quickCommandDialog').close();openExisting('customers','newCustomerBtn')}},
  {icon:'▣',label:'Novo pedido',sub:'Pedido manual',keys:'pedido',run:()=>{$('quickCommandDialog').close();openExisting('orders','newOrderBtn')}},
  {icon:'◇',label:'Novo atendimento',sub:'Adicionar ao CRM',keys:'lead atendimento crm',run:()=>{$('quickCommandDialog').close();openExisting('funnel','newLeadBtn')}},
  {icon:'R$',label:'Novo lançamento',sub:'Entrada ou saída',keys:'lançamento lancamento caixa despesa entrada saída saida',run:()=>{$('quickCommandDialog').close();openExisting('ledger','newMovementBtn')}},
  {icon:'◷',label:'Abrir Hoje',sub:'Centro operacional',keys:'hoje dia tarefas',run:()=>{$('quickCommandDialog').close();showToday()}}
]}
function renderCommand(query){const q=String(query||'').trim().toLowerCase();commandRows=[];const commands=commandDefinitions().filter(c=>!q||`${c.label} ${c.sub} ${c.keys}`.toLowerCase().includes(q));commands.forEach(c=>commandRows.push({...c,type:'Ação'}));if(q.startsWith('tarefa ')&&q.length>7)commandRows.unshift({icon:'✓',label:`Criar tarefa: ${query.slice(7)}`,sub:'Interpretar texto e revisar antes de salvar',type:'Comando',run:()=>{$('quickCommandDialog').close();openQuickTask({text:query.slice(7)})}});if(q.startsWith('lançar ')||q.startsWith('lancar ')){const raw=query.replace(/^lan[cç]ar\s+/i,''),m=raw.match(/(?:r\$\s*)?(\d+(?:[.,]\d{1,2})?)/i),amount=m?Number(m[1].replace(',','.')):null,desc=raw.replace(m?.[0]||'','').trim();commandRows.unshift({icon:'R$',label:`Lançar ${amount?brl(amount):'movimentação'}`,sub:desc||'Abrir lançamento com os dados reconhecidos',type:'Comando',run:()=>{$('quickCommandDialog').close();openExisting('ledger','newMovementBtn',()=>{const f=$('entityDialog');if(amount)f?.querySelector('[name="amount"]')&&(f.querySelector('[name="amount"]').value=amount);if(desc)f?.querySelector('[name="description"]')&&(f.querySelector('[name="description"]').value=desc)})}})}
  if(q){snapshot.customers.filter(x=>[x.name,x.whatsapp,x.email].some(v=>String(v||'').toLowerCase().includes(q))).slice(0,8).forEach(x=>commandRows.push({icon:'◎',label:x.name,sub:x.whatsapp||x.email||'Cliente',type:'Cliente',run:()=>{$('quickCommandDialog').close();clickNav('customers')}}));snapshot.orders.filter(x=>String(x.code||'').toLowerCase().includes(q)||customerById(x.customer_id).toLowerCase().includes(q)).slice(0,8).forEach(x=>commandRows.push({icon:'▣',label:x.code||'Pedido',sub:`${customerById(x.customer_id)} · ${ORDER_STATUS[x.status]||x.status}`,type:'Pedido',run:()=>{$('quickCommandDialog').close();clickNav('orders')}}));snapshot.quotes.filter(x=>String(x.code||'').toLowerCase().includes(q)||customerById(x.customer_id).toLowerCase().includes(q)).slice(0,8).forEach(x=>commandRows.push({icon:'▤',label:x.code||'Orçamento',sub:`${customerById(x.customer_id)} · ${brl(x.total)}`,type:'Orçamento',run:()=>{$('quickCommandDialog').close();clickNav('quotes')}}));snapshot.tasks.filter(x=>String(x.title||'').toLowerCase().includes(q)).slice(0,8).forEach(x=>commandRows.push({icon:'✓',label:x.title,sub:x.assignee||'Tarefa',type:'Tarefa',run:()=>{$('quickCommandDialog').close();clickNav('tasks')}}));snapshot.products.filter(x=>[x.name,x.category].some(v=>String(v||'').toLowerCase().includes(q))).slice(0,8).forEach(x=>commandRows.push({icon:'▦',label:x.name,sub:x.category||'Produto',type:'Produto',run:()=>{$('quickCommandDialog').close();clickNav('catalog')}}))}
  commandIndex=0;const grouped=[];for(const row of commandRows){let g=grouped.find(x=>x.type===row.type);if(!g){g={type:row.type,rows:[]};grouped.push(g)}g.rows.push(row)}let offset=0;$('quickCommandResults').innerHTML=grouped.map(g=>`<div class="quick-command-group">${esc(g.type)}</div>${g.rows.map((r,i)=>`<button class="quick-command-item ${offset+i===0?'active':''}" data-command-index="${offset+i}"><i>${esc(r.icon)}</i><div><b>${esc(r.label)}</b><small>${esc(r.sub)}</small></div>${r.type==='Ação'?'<em>abrir</em>':''}</button>`).join('')}${(()=>{offset+=g.rows.length;return''})()}`).join('')||'<div class="today-empty">Nada encontrado.</div>';$$('[data-command-index]').forEach(b=>b.onclick=()=>commandRows[Number(b.dataset.commandIndex)]?.run?.())}
function moveCommand(delta){if(!commandRows.length)return;commandIndex=(commandIndex+delta+commandRows.length)%commandRows.length;$$('[data-command-index]').forEach(b=>b.classList.toggle('active',Number(b.dataset.commandIndex)===commandIndex));document.querySelector(`[data-command-index="${commandIndex}"]`)?.scrollIntoView({block:'nearest'})}

function decorateContexts(){const add=(anchor,html)=>{if(!anchor||anchor.parentElement.querySelector(html.selector))return;anchor.insertAdjacentHTML('beforebegin',html.markup)};$$('#customersList .customer-edit').forEach(b=>{add(b,{selector:`.quick-task-customer[data-id="${b.dataset.id}"]`,markup:`<button class="small-btn quick-context-btn quick-task-customer" data-id="${b.dataset.id}">+ Tarefa</button><button class="small-btn quick-context-btn quick-quote-customer" data-id="${b.dataset.id}">Orçar</button>`})});$$('#ordersList .order-edit').forEach(b=>add(b,{selector:`.quick-task-order[data-id="${b.dataset.id}"]`,markup:`<button class="small-btn quick-context-btn quick-task-order" data-id="${b.dataset.id}">+ Tarefa</button>`}));$$('#quotesList .quote-edit').forEach(b=>add(b,{selector:`.quick-task-quote[data-id="${b.dataset.id}"]`,markup:`<button class="small-btn quick-context-btn quick-task-quote" data-id="${b.dataset.id}">+ Tarefa</button>`}));$$('.quick-task-customer').forEach(b=>b.onclick=()=>openQuickTask({customer_id:b.dataset.id}));$$('.quick-quote-customer').forEach(b=>b.onclick=()=>openExisting('quotes','newQuoteBtn',()=>{const select=$('entityDialog')?.querySelector('[name="customer_id"]');if(select)select.value=b.dataset.id}));$$('.quick-task-order').forEach(b=>b.onclick=()=>openQuickTask({order_id:b.dataset.id}));$$('.quick-task-quote').forEach(b=>b.onclick=async()=>{await loadSnapshot();const q=snapshot.quotes.find(x=>x.id===b.dataset.id);openQuickTask({customer_id:q?.customer_id||null,title:`Follow-up ${q?.code||'orçamento'}`})})}

function refreshMainSoon(){setTimeout(()=>{$('refreshBtn')?.click();setTimeout(renderQuickSurfaces,450)},60)}
function wireExistingUi(){const primary=$('newPrimaryBtn');if(primary){primary.textContent='+ Criar';primary.title='Criar venda, tarefa, orçamento, cliente e mais';primary.onclick=e=>{e.preventDefault();e.stopPropagation();toggleCreateMenu()}}const search=$('globalSearchBtn');if(search){search.querySelector('span')&&(search.querySelector('span').textContent='Buscar ou comandar...');search.onclick=e=>{e.preventDefault();openCommand()}}const nt=$('newTaskBtn');if(nt)nt.onclick=()=>openQuickTask();$('refreshBtn')?.addEventListener('click',()=>setTimeout(renderQuickSurfaces,450));document.addEventListener('click',e=>{if(!e.target.closest('#quickCreateMenu')&&!e.target.closest('#newPrimaryBtn'))closeCreateMenu()})}
function wireShortcuts(){window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();e.stopImmediatePropagation();openCommand();return}if(e.key==='Escape'){closeCreateMenu();return}if(e.ctrlKey||e.metaKey||e.altKey||isTypingTarget(e.target)||dialogOpen())return;const k=e.key.toLowerCase();if(k==='t'){e.preventDefault();openQuickTask()}else if(k==='n'){e.preventDefault();clickNav('sale')}else if(k==='o'){e.preventDefault();openExisting('quotes','newQuoteBtn')}else if(k==='c'){e.preventDefault();openExisting('customers','newCustomerBtn')}},true)}

function observeRenders(){let timer=null;const main=document.querySelector('.main');if(!main)return;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>{decorateContexts();if(!document.querySelector('#section-dashboard #dashboardDay'))injectDashboardDay()},80)}).observe(main,{subtree:true,childList:true})}

async function init(){injectStyle();injectCreateMenu();injectToday();injectDashboardDay();injectQuickTaskDialog();injectCommandDialog();wireExistingUi();wireShortcuts();observeRenders();await renderQuickSurfaces();setInterval(()=>{if(document.visibilityState==='visible')renderQuickSurfaces()},60000)}

if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0));else setTimeout(init,0);
