import {jsPDF} from 'https://esm.sh/jspdf@2.5.2';
import {supabase,db} from './erp-db.js';

const $=id=>document.getElementById(id);
const $$=sel=>[...document.querySelectorAll(sel)];
const one=sel=>document.querySelector(sel);
const brl=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date());
const META='[[PACO_V8]]';
let mounting=false,mounted=false,wrapped=false,lastSale=null,graphMode='current',graphMonth=null;

function injectCss(){if(one('link[data-sale-flow-v8]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./sale-flow-v7.css?build=20260901-1100';l.dataset.saleFlowV8='1';document.head.appendChild(l)}
function toast(msg,error=false){const e=$('toast');if(!e)return;e.textContent=msg;e.className=`toast show${error?' error':''}`;clearTimeout(window.__v8toast);window.__v8toast=setTimeout(()=>e.className='toast',3400)}
function money(text){return Number(String(text||'').replace(/[^\d,-]/g,'').replace(/\./g,'').replace(',','.'))||0}
function total(){return money($('saleTotal')?.textContent)}
function phone(v){return String(v||'').replace(/\D/g,'')}
async function user(){return(await supabase.auth.getSession()).data.session?.user||null}
async function settings(){const u=await user();if(!u)return{};const{data}=await supabase.from('company_settings').select('*').eq('user_id',u.id).maybeSingle();return data||{}}
function companyAddress(s){return[s.address,s.city&&s.state?`${s.city}/${s.state}`:s.city||s.state,s.zip_code&&`CEP ${s.zip_code}`].filter(Boolean).join(' · ')||'Endereço da gráfica ainda não configurado.'}
function dayOffset(n){const d=new Date();d.setDate(d.getDate()+n);return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(d)}
function parseMeta(note=''){const s=String(note||''),i=s.indexOf(META);if(i<0)return{note:s.trim()};try{return{...JSON.parse(s.slice(i+META.length)),note:s.slice(0,i).trim()}}catch{return{note:s.trim()}}}

function purgeOldSaleEnhancements(){
  const section=$('section-sale');if(!section)return;
  section.querySelectorAll('#saleLogisticsPanel,[data-sale-v7-logistics],[data-sale-v8-logistics]').forEach(el=>el.remove());
  section.querySelectorAll('#saleEntryBlock,[data-sale-v7-entry],[data-sale-v8-entry]').forEach(el=>el.remove());
  const item=$('saleItems')?.closest('.panel');item?.querySelector('.section-title b')?.replaceChildren(document.createTextNode('02'));
}
async function mountSale(){
  if(mounted||mounting)return mounted;const section=$('section-sale'),item=$('saleItems')?.closest('.panel'),stack=section?.querySelector('.stack');if(!section||!item||!stack)return false;
  mounting=true;
  try{
    purgeOldSaleEnhancements();const s=await settings();
    const first=stack.querySelector('.panel');first?.querySelector('.section-title p')?.replaceChildren(document.createTextNode('Cliente, responsável e contato.'));if($('saleNote'))$('saleNote').placeholder='Acabamento, arte, detalhes e observações...';
    item.insertAdjacentHTML('beforebegin',`<article class="panel sale-logistics-panel" data-sale-v8-logistics="1"><div class="section-title"><b>02</b><div><h3>Prazo, entrega e pagamento</h3><p>Preencha só o necessário.</p></div></div><div class="sale-deadline-row"><label>Prazo<input id="saleDueDate" type="date" value="${dayOffset(2)}"></label><div class="sale-date-shortcuts"><button type="button" data-v8-days="1">Amanhã</button><button type="button" data-v8-days="2" class="active">+2 dias</button><button type="button" data-v8-days="3">+3 dias</button><button type="button" data-v8-days="7">+7 dias</button></div><label>Horário<input id="saleDueTime" type="time" value="17:00"></label></div><div class="sale-choice-grid"><div class="sale-choice"><span>Como o cliente recebe?</span><div class="segmented"><button type="button" class="active" data-v8-fulfillment="pickup">Retirada</button><button type="button" data-v8-fulfillment="delivery">Entrega</button></div><input id="saleFulfillment" type="hidden" value="pickup"></div><label>Pagamento<select id="salePaymentCondition"><option value="entrada_retirada">Entrada + saldo na retirada</option><option value="avista">À vista</option><option value="retirada">Pagar tudo na retirada</option><option value="entrada_entrega">Entrada + saldo na entrega</option><option value="entrega">Pagar tudo na entrega</option></select></label></div><div id="salePickupInfo" class="sale-pickup-info"><span>LOCAL DE RETIRADA</span><b>${esc(s.trade_name||'Papel e Código')}</b><small>${esc(companyAddress(s))}</small></div><div id="saleDeliveryFields" class="sale-delivery-fields hidden"><div class="sale-delivery-title"><b>Endereço de entrega</b><small>Preencha somente para entrega.</small></div><div class="form-grid three"><label>Endereço<input id="saleDeliveryAddress"></label><label>Número<input id="saleDeliveryNumber"></label><label>Complemento<input id="saleDeliveryComplement"></label></div><div class="form-grid four"><label>Bairro<input id="saleDeliveryDistrict"></label><label>Cidade<input id="saleDeliveryCity"></label><label>UF<input id="saleDeliveryState" maxlength="2"></label><label>CEP<input id="saleDeliveryZip"></label></div><label class="delivery-fee">Taxa de entrega<input id="saleDeliveryFee" type="number" min="0" step="0.01" value="0"></label></div></article>`);
    item.querySelector('.section-title b')?.replaceChildren(document.createTextNode('03'));item.querySelector('.section-title p')?.replaceChildren(document.createTextNode('O que será produzido.'));
    const payment=$('salePayment')?.closest('label');payment?.insertAdjacentHTML('afterend',`<div class="sale-entry-block" data-sale-v8-entry="1"><label id="saleEntryLabel">Entrada<input id="saleEntry" type="number" min="0" step="0.01" value="0"></label><div class="sale-balance-preview"><span>Saldo restante</span><strong id="saleRemaining">R$ 0,00</strong><small id="saleBalanceHint">Saldo na retirada</small></div></div>`);
    $$('[data-v8-days]').forEach(b=>b.onclick=()=>{$('saleDueDate').value=dayOffset(Number(b.dataset.v8Days));$$('[data-v8-days]').forEach(x=>x.classList.toggle('active',x===b))});
    $$('[data-v8-fulfillment]').forEach(b=>b.onclick=()=>{$$('[data-v8-fulfillment]').forEach(x=>x.classList.toggle('active',x===b));$('saleFulfillment').value=b.dataset.v8Fulfillment;syncFulfillment()});
    $('salePaymentCondition').onchange=syncPayment;$('saleEntry').oninput=syncPayment;$('saleDeliveryFee').oninput=syncPayment;$('saleDiscount')?.addEventListener('input',()=>setTimeout(syncPayment,0));$('saleItems')?.addEventListener('input',()=>setTimeout(syncPayment,0));
    syncFulfillment();mounted=true;return true;
  }finally{mounting=false}
}
function syncFulfillment(){const delivery=$('saleFulfillment')?.value==='delivery';$('saleDeliveryFields')?.classList.toggle('hidden',!delivery);$('salePickupInfo')?.classList.toggle('hidden',delivery);const c=$('salePaymentCondition');if(c){if(delivery&&c.value==='entrada_retirada')c.value='entrada_entrega';if(delivery&&c.value==='retirada')c.value='entrega';if(!delivery&&c.value==='entrada_entrega')c.value='entrada_retirada';if(!delivery&&c.value==='entrega')c.value='retirada'}syncPayment()}
function syncPayment(){const e=$('saleEntry');if(!e)return;const grand=total()+Number($('saleDeliveryFee')?.value||0),c=$('salePaymentCondition')?.value||'entrada_retirada',needs=c.startsWith('entrada_');one('[data-sale-v8-entry]')?.classList.toggle('entry-not-needed',!needs);$('saleEntryLabel')?.classList.toggle('hidden-field',!needs);let v=Number(e.value||0);if(c==='avista'){v=grand;e.value=grand.toFixed(2);e.readOnly=true}else if(['retirada','entrega'].includes(c)){v=0;e.value='0';e.readOnly=true}else{e.readOnly=false;v=Math.min(grand,Math.max(0,v));e.value=v.toFixed(2)}$('saleRemaining').textContent=brl(Math.max(0,grand-v));$('saleBalanceHint').textContent=({avista:'Pagamento à vista',entrada_retirada:'Saldo na retirada',entrada_entrega:'Saldo na entrega',retirada:'Pagamento na retirada',entrega:'Pagamento na entrega'})[c]||''}
function saleMeta(){const base=total(),fee=Number($('saleDeliveryFee')?.value||0),grand=base+fee,c=$('salePaymentCondition')?.value||'entrada_retirada',entry=c==='avista'?grand:['retirada','entrega'].includes(c)?0:Number($('saleEntry')?.value||0),f=$('saleFulfillment')?.value||'pickup';return{version:8,due_date:$('saleDueDate')?.value||null,due_time:$('saleDueTime')?.value||null,fulfillment:f,payment_condition:c,entry_amount:Math.min(grand,Math.max(0,entry)),remaining_amount:Math.max(0,grand-entry),delivery_fee:fee,delivery:f==='delivery'?{address:$('saleDeliveryAddress')?.value.trim()||'',number:$('saleDeliveryNumber')?.value.trim()||'',complement:$('saleDeliveryComplement')?.value.trim()||'',district:$('saleDeliveryDistrict')?.value.trim()||'',city:$('saleDeliveryCity')?.value.trim()||'',state:$('saleDeliveryState')?.value.trim().toUpperCase()||'',zip:$('saleDeliveryZip')?.value.trim()||''}:null}}
function validate(){if(!$('saleDueDate')?.value){toast('Escolha o prazo do material.',true);return false}if($('saleFulfillment')?.value==='delivery'&&!$('saleDeliveryAddress')?.value.trim()){toast('Informe o endereço de entrega.',true);return false}return true}
async function newestSale(){const u=await user();if(!u)return null;const{data,error}=await supabase.from('sales').select('*,sale_items(*)').eq('user_id',u.id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data}
async function syncCustomer(sale,m){if(!sale.customer_name)return null;const u=await user();if(!u)return null;db.setUser(u);await db.detectERP();const rows=await db.list('customers'),p=phone(sale.customer_phone),name=String(sale.customer_name).trim();let c=rows.find(x=>String(x.name||'').trim().toLowerCase()===name.toLowerCase()||(p&&[x.phone,x.whatsapp].map(phone).includes(p)));const d=m.delivery||{},payload={name,whatsapp:sale.customer_phone||null,seller_name:sale.seller_name||null,source:'Venda rápida',active:true,address:d.address?[d.address,d.number,d.complement].filter(Boolean).join(', '):c?.address||null,city:d.city||c?.city||null,state:d.state||c?.state||null,zip_code:d.zip||c?.zip_code||null};if(!c)c=await db.insert('customers',payload);return c}
async function syncLead(sale,m){if(!sale.customer_name)return;const u=await user();if(!u)return;const marker=`[VENDA:${sale.id}]`,{data}=await supabase.from('leads').select('id').eq('user_id',u.id).ilike('note',`%${marker}%`).limit(1);if(data?.length)return;await supabase.from('leads').insert({user_id:u.id,customer_name:sale.customer_name,customer_phone:sale.customer_phone||null,service_interest:(sale.sale_items||[]).map(i=>i.description).filter(Boolean).slice(0,3).join(' + ')||'Venda rápida',estimated_value:Number(sale.total||0)+Number(m.delivery_fee||0),seller_name:sale.seller_name||null,stage:'aprovado',note:`${marker}\nCriado automaticamente pela venda.`})}
async function syncFinance(sale,c,m){const u=await user();if(!u)return;db.setUser(u);await db.detectERP();const grand=Number(sale.total||0)+Number(m.delivery_fee||0),entry=Math.min(grand,Number(m.entry_amount||0)),remaining=Math.max(0,grand-entry),key=`Venda ${String(sale.id).slice(0,8).toUpperCase()}`,recs=await db.list('receivables');if(!recs.some(r=>String(r.description||'').includes(key)))await db.insert('receivables',{customer_id:c?.id||null,description:`${key} · ${sale.customer_name||'Balcão'}`,due_date:m.due_date||localDate(),amount:grand,received_amount:entry,status:remaining<=0?'paid':entry>0?'partial':'pending',payment_method:sale.payment_method||null});if(entry>0){const{data}=await supabase.from('cash_movements').select('id').eq('user_id',u.id).eq('description',`${key} · entrada`).limit(1);if(!data?.length)await supabase.from('cash_movements').insert({user_id:u.id,type:'entrada',amount:entry,category:'Venda',description:`${key} · entrada`,nature:'operational'})}}
async function postSale(m){try{const sale=await newestSale();if(!sale)return;lastSale=sale;const key=`paco_v8_${sale.id}`;if(localStorage.getItem(key)!=='1'){const c=await syncCustomer(sale,m);await syncLead(sale,m);await syncFinance(sale,c,m);localStorage.setItem(key,'1')}if($('receiptTitle'))$('receiptTitle').textContent=`Venda registrada · ${m.remaining_amount>0?`saldo ${brl(m.remaining_amount)}`:'paga'}`;const p=$('receiptDialog')?.querySelector('.receipt-success p');if(p)p.textContent=m.remaining_amount>0?`Entrada ${brl(m.entry_amount)} · restante ${brl(m.remaining_amount)}.`:'Pagamento registrado integralmente.';setTimeout(renderGraph,200)}catch(e){console.error(e);toast('Venda salva, mas CRM/financeiro não sincronizaram.',true)}}
function wrapFinish(){const b=$('finishSaleBtn');if(!b||b.dataset.v8==='1'||typeof b.onclick!=='function')return false;const original=b.onclick;b.dataset.v8='1';b.onclick=async function(e){if(!validate())return;syncPayment();const m=saleMeta(),note=$('saleNote'),plain=note?.value.trim()||'';if(note)note.value=`${plain}${plain?'\n':''}${META}${JSON.stringify(m)}`;await original.call(this,e);if($('receiptDialog')?.open)await postSale(m)};wrapped=true;return true}

function conditionName(v){return({avista:'À vista',entrada_retirada:'Entrada + saldo na retirada',entrada_entrega:'Entrada + saldo na entrega',retirada:'Pagamento na retirada',entrega:'Pagamento na entrega'})[v]||'Não informado'}
function fulfillmentName(v){return v==='delivery'?'Entrega':'Retirada na gráfica'}
function deliveryAddress(m,s){if(m.fulfillment!=='delivery')return companyAddress(s);const d=m.delivery||{};return[[d.address,d.number].filter(Boolean).join(', '),d.complement,d.district,[d.city,d.state].filter(Boolean).join('/'),d.zip&&`CEP ${d.zip}`].filter(Boolean).join(' · ')}
function addText(doc,text,x,y,max=178){const lines=doc.splitTextToSize(String(text||''),max);doc.text(lines,x,y);return y+lines.length*5}
async function receipt(sale){const m=parseMeta(sale.note),s=await settings(),doc=new jsPDF({unit:'mm',format:'a4'}),grand=Number(sale.total||0)+Number(m.delivery_fee||0),entry=Number(m.entry_amount||0),remaining=Math.max(0,Number(m.remaining_amount??grand-entry));doc.setFillColor(8,23,43);doc.rect(0,0,210,38,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(17);doc.text(s.trade_name||'Papel e Código',16,15);doc.setFontSize(8);doc.setFont('helvetica','normal');const head=[s.legal_name,s.cnpj&&`CNPJ ${s.cnpj}`,s.state_registration&&`IE ${s.state_registration}`].filter(Boolean).join(' · ');if(head)doc.text(head,16,22);doc.setTextColor(223,240,31);doc.setFont('helvetica','bold');doc.text('RECIBO / COMPROVANTE DE PEDIDO',16,30);doc.setTextColor(22,34,50);let y=49;doc.setFontSize(9);doc.text(`Venda ${String(sale.id).slice(0,8).toUpperCase()}`,16,y);doc.setFont('helvetica','normal');doc.text(new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(sale.created_at)),194,y,{align:'right'});y+=11;doc.setFont('helvetica','bold');doc.text('CLIENTE',16,y);y+=6;doc.setFont('helvetica','normal');y=addText(doc,`Nome: ${sale.customer_name||'Venda balcão'}`,16,y);if(sale.customer_phone)y=addText(doc,`WhatsApp: ${sale.customer_phone}`,16,y);y=addText(doc,`Responsável: ${sale.seller_name||'—'}`,16,y);y+=4;doc.setFont('helvetica','bold');doc.text('ITENS',16,y);y+=7;doc.setFont('helvetica','normal');for(const i of sale.sale_items||[]){doc.text(`${i.quantity} × ${String(i.description||'Item').slice(0,75)}`,16,y);doc.text(brl(i.total),194,y,{align:'right'});y+=7}y+=4;doc.setFont('helvetica','bold');doc.setFontSize(12);doc.text(`TOTAL ${brl(grand)}`,194,y,{align:'right'});y+=12;doc.setFontSize(9);doc.text('PRAZO E RECEBIMENTO',16,y);y+=6;doc.setFont('helvetica','normal');doc.text(`Previsão: ${m.due_date?new Date(`${m.due_date}T12:00:00`).toLocaleDateString('pt-BR'):'—'}${m.due_time?` às ${m.due_time}`:''}`,16,y);y+=6;doc.text(`Forma: ${fulfillmentName(m.fulfillment)}`,16,y);y+=6;y=addText(doc,`${m.fulfillment==='delivery'?'Endereço de entrega':'Local de retirada'}: ${deliveryAddress(m,s)}`,16,y);y+=4;doc.setFont('helvetica','bold');doc.text('PAGAMENTO',16,y);y+=6;doc.setFont('helvetica','normal');doc.text(`Condição: ${conditionName(m.payment_condition)}`,16,y);y+=6;doc.text(`Entrada: ${brl(entry)}`,16,y);y+=6;doc.setFont('helvetica','bold');doc.text(`Saldo: ${brl(remaining)}`,16,y);y+=9;if(m.note){doc.setFont('helvetica','bold');doc.text('OBSERVAÇÕES',16,y);y+=6;doc.setFont('helvetica','normal');y=addText(doc,m.note,16,y)}y+=8;doc.setFontSize(8);for(const line of [companyAddress(s),s.whatsapp&&`WhatsApp ${s.whatsapp}`,s.email,s.instagram,s.website,s.pix_key&&`PIX: ${s.pix_key}`].filter(Boolean))y=addText(doc,line,16,y);if(s.receipt_footer){y+=2;doc.setFont('helvetica','bold');addText(doc,s.receipt_footer,16,y)}return doc}
function interceptReceipt(){const pdf=$('receiptPdfBtn');if(pdf&&!pdf.dataset.v8){pdf.dataset.v8='1';pdf.addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();const sale=lastSale||await newestSale();if(!sale)return;(await receipt(sale)).save(`REC-${String(sale.id).slice(0,8).toUpperCase()}.pdf`)},true)}}

function monthKey(offset=0){const d=new Date();d.setDate(1);d.setMonth(d.getMonth()+offset);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function prevKey(key){const[y,m]=key.split('-').map(Number),d=new Date(y,m-1,1);d.setMonth(d.getMonth()-1);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function monthLabel(key){const[y,m]=key.split('-').map(Number);return new Intl.DateTimeFormat('pt-BR',{month:'short',year:'numeric'}).format(new Date(y,m-1,1)).replace('.','').replace(/^./,c=>c.toUpperCase())}
function range(key){const[y,m1]=key.split('-').map(Number),m=m1-1,days=new Date(y,m+1,0).getDate(),pad=n=>String(n).padStart(2,'0');return{days,start:`${y}-${pad(m+1)}-01T00:00:00-03:00`,end:`${y}-${pad(m+1)}-${pad(days)}T23:59:59-03:00`}}
function cumulative(rows,days){const a=Array(days).fill(0);for(const r of rows){const i=new Date(r.created_at).getDate()-1;if(i>=0&&i<days)a[i]+=r.type==='entrada'?Number(r.amount||0):-Number(r.amount||0)}let s=0;return a.map(v=>s+=v)}
async function monthRows(u,key){const r=range(key),{data,error}=await supabase.from('cash_movements').select('type,amount,created_at').eq('user_id',u.id).gte('created_at',r.start).lte('created_at',r.end).order('created_at');if(error)throw error;return{r,rows:data||[]}}
function path(vals,w,h,min,max){if(!vals.length)return'';const span=max-min||1,step=w/Math.max(1,vals.length-1);return vals.map((v,i)=>`${i?'L':'M'} ${(i*step).toFixed(1)} ${(h-(v-min)/span*h).toFixed(1)}`).join(' ')}
async function graphData(key,project){const u=await user();if(!u)return null;const pk=prevKey(key),[a,b]=await Promise.all([monthRows(u,key),monthRows(u,pk)]),cur=cumulative(a.rows,a.r.days),previous=cumulative(b.rows,b.r.days),isCurrent=key===monthKey(0),n=isCurrent?Math.min(new Date().getDate(),a.r.days):a.r.days,actual=cur.slice(0,n),close=actual.at(-1)||0,avg=close/Math.max(1,n),projection=project&&isCurrent?Array.from({length:a.r.days},(_,i)=>i<n?actual[i]:close+avg*(i-n+1)):[];return{key,pk,r:a.r,actual,previous,projection,close,prevClose:previous.at(-1)||0,projected:projection.at(-1)||close}}
function injectGraph(){const section=$('section-today');if(!section||$('todayFinanceGraph'))return;graphMonth=graphMonth||monthKey(-1);section.insertAdjacentHTML('afterbegin',`<article id="todayFinanceGraph" class="today-finance-graph"><div class="finance-graph-head"><div><span>FINANCEIRO</span><h3>Caixa e projeção</h3></div><div class="finance-graph-tabs"><button class="active" data-v8-mode="current">Este mês</button><button data-v8-mode="history">Meses anteriores</button><select id="financeHistoryMonth" class="hidden">${Array.from({length:12},(_,i)=>{const k=monthKey(-(i+1));return`<option value="${k}">${monthLabel(k)}</option>`}).join('')}</select></div><div class="finance-graph-kpis"><div><small id="fgLabelCurrent">Caixa do mês</small><b id="fgCurrent">R$ 0</b></div><div><small id="fgLabelProjection">Projeção</small><b id="fgProjection">R$ 0</b></div><div><small id="fgLabelPrevious">Mês anterior</small><b id="fgPrevious">R$ 0</b></div></div></div><div class="finance-graph-canvas"><svg id="fgSvg" viewBox="0 0 1000 320" preserveAspectRatio="none"></svg></div><div class="finance-graph-legend"><span class="real" id="fgLegendReal">Caixa real</span><span class="projection" id="fgLegendProjection">Projeção do mês</span><span class="previous" id="fgLegendPrevious">Mês anterior</span></div></article>`);$$('[data-v8-mode]').forEach(b=>b.onclick=()=>{graphMode=b.dataset.v8Mode;$$('[data-v8-mode]').forEach(x=>x.classList.toggle('active',x===b));$('financeHistoryMonth').classList.toggle('hidden',graphMode!=='history');renderGraph()});$('financeHistoryMonth').value=graphMonth;$('financeHistoryMonth').onchange=e=>{graphMonth=e.target.value;renderGraph()}}
async function renderGraph(){injectGraph();if(!$('fgSvg'))return;try{const hist=graphMode==='history',d=await graphData(hist?graphMonth:monthKey(0),!hist);if(!d)return;$('fgCurrent').textContent=brl(d.close);$('fgPrevious').textContent=brl(d.prevClose);if(hist){const v=d.prevClose?((d.close-d.prevClose)/Math.abs(d.prevClose))*100:0;$('fgProjection').textContent=`${v>=0?'+':''}${v.toFixed(1).replace('.',',')}%`;$('fgLabelCurrent').textContent=monthLabel(d.key);$('fgLabelProjection').textContent='Variação';$('fgLabelPrevious').textContent=monthLabel(d.pk);$('fgLegendReal').textContent=monthLabel(d.key);$('fgLegendPrevious').textContent=monthLabel(d.pk);$('fgLegendProjection').classList.add('hidden')}else{$('fgProjection').textContent=brl(d.projected);$('fgLabelCurrent').textContent='Caixa do mês';$('fgLabelProjection').textContent='Projeção';$('fgLabelPrevious').textContent='Mês anterior';$('fgLegendReal').textContent='Caixa real';$('fgLegendPrevious').textContent='Mês anterior';$('fgLegendProjection').classList.remove('hidden')}const all=[...d.actual,...d.previous,...d.projection,0].filter(Number.isFinite),min=Math.min(...all),max=Math.max(...all),h=225,pa=path(d.actual,1000,h,min,max),pp=path(d.previous,1000,h,min,max),pj=d.projection.length?path(d.projection,1000,h,min,max):'',zero=(h-(0-min)/(max-min||1)*h).toFixed(1),mid=Math.ceil(d.r.days/2);$('fgSvg').innerHTML=`<g transform="translate(0 25)"><line x1="0" y1="${zero}" x2="1000" y2="${zero}" class="fg-zero"/><path d="${pp}" class="fg-line fg-prev"/>${pj?`<path d="${pj}" class="fg-line fg-proj"/>`:''}<path d="${pa}" class="fg-line fg-real"/></g><g class="fg-days"><text x="0" y="305">1</text><text x="500" y="305" text-anchor="middle">${mid}</text><text x="1000" y="305" text-anchor="end">${d.r.days}</text></g>`}catch(e){console.warn('Financeiro V8',e)}}

function setup(){injectCss();purgeOldSaleEnhancements();let tries=0;const t=setInterval(async()=>{tries++;if(!mounted)await mountSale();if(!wrapped)wrapFinish();interceptReceipt();injectGraph();if($('fgSvg'))renderGraph();if((mounted&&wrapped&&$('fgSvg'))||tries>120)clearInterval(t)},125);setInterval(()=>{if(document.visibilityState==='visible')renderGraph()},60000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
